sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
script: "bundle exec rspec"
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile