sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - gem cleanup bundler
script: "bundle exec rspec"
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile